/* SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (c) 2026 Ed Hodapp
 *
 * Host-side test driver for the per-arch crc32_ieee_802_3 assembly
 * routine. Runs a small vector set and exits non-zero on the first
 * mismatch. One binary per arch — the x86_64 binary links
 * arch/x86_64/crypto/build/crc32_ieee.o and runs natively; the
 * aarch64 binary cross-builds with aarch64-linux-gnu-gcc and runs
 * under qemu-aarch64-static.
 *
 * Contract probed:
 *   uint32_t crc32_ieee_802_3(const void *data, size_t len);
 * IEEE 802.3 §3.2.9, polynomial 0xEDB88320 reflected, init/final XOR
 * 0xFFFFFFFF, zero-length → 0x00000000.
 */
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "vectors.h"

/* Defined in the linked assembly object. */
extern uint32_t crc32_ieee_802_3(const void *data, size_t len);

static const unsigned char vec_a[]            = "a";
static const unsigned char vec_abc[]          = "abc";
static const unsigned char vec_msg_digest[]   = "message digest";
static const unsigned char vec_alphabet[]     = "abcdefghijklmnopqrstuvwxyz";

static unsigned char vec_1024_zero[1024];
static unsigned char vec_1024_ff[1024];

static const struct crc_vector VECTORS[] = {
    { "empty",          NULL,           0,    0x00000000u },
    { "a",              vec_a,          1,    0xE8B7BE43u },
    { "abc",            vec_abc,        3,    0x352441C2u },
    { "message digest", vec_msg_digest, 14,   0x20159D7Fu },
    { "alphabet",       vec_alphabet,   26,   0x4C2750BDu },
    { "1024 x 0x00",    vec_1024_zero,  1024, 0xEFB5AF2Eu },
    { "1024 x 0xFF",    vec_1024_ff,    1024, 0xB83AFFF4u },
};
#define N_VECTORS (sizeof VECTORS / sizeof VECTORS[0])

int main(void) {
    memset(vec_1024_zero, 0x00, sizeof vec_1024_zero);
    memset(vec_1024_ff,   0xFF, sizeof vec_1024_ff);

    int failures = 0;
    for (size_t i = 0; i < N_VECTORS; ++i) {
        const struct crc_vector *v = &VECTORS[i];
        uint32_t got = crc32_ieee_802_3(v->data, v->len);
        const char *tag = (got == v->expected) ? "ok  " : "FAIL";
        printf("%s  %-16s  len=%4zu  exp=0x%08X  got=0x%08X\n",
               tag, v->name, v->len, v->expected, got);
        if (got != v->expected) {
            ++failures;
        }
    }

    static const unsigned char pangram[] =
        "The quick brown fox jumps over the lazy dog";
    const size_t plen = sizeof pangram - 1;  /* strip NUL */
    const uint32_t expected_pangram = 0x414FA339u;
    uint32_t got_pangram = crc32_ieee_802_3(pangram, plen);
    const char *ptag =
        (got_pangram == expected_pangram) ? "ok  " : "FAIL";
    printf("%s  %-16s  len=%4zu  exp=0x%08X  got=0x%08X\n",
           ptag, "pangram", plen, expected_pangram, got_pangram);
    if (got_pangram != expected_pangram) {
        ++failures;
    }

    /* Length sweep 0..31 exercises every residue class for both the
     * main-loop start condition and the byte tail. Expected values
     * were generated by Python zlib.crc32 against the same buffer. */
    unsigned char buf[32];
    for (size_t i = 0; i < sizeof buf; ++i) {
        buf[i] = (unsigned char)(i * 37u + 13u);
    }
    static const uint32_t pattern_expected[32] = {
        0x00000000u, 0xACB39330u, 0x3CA03D32u, 0xEFE6DA67u,
        0x5888C0BBu, 0x2F389E37u, 0x18971599u, 0x6C116888u,
        0x2CBAE593u, 0xED9B53B5u, 0xE25A8B37u, 0xAAE77CA4u,
        0xD2A808F1u, 0xFAD2FF1Bu, 0x1F2F3BE1u, 0x81AE5386u,
        0xFE5ADF55u, 0xDC273D60u, 0x9CDA4BE4u, 0x3D4B25ECu,
        0xE9518460u, 0x55E31DDBu, 0x3782B29Du, 0xED806BE2u,
        0xD1598DEAu, 0x0FDECAC9u, 0x06B601A5u, 0x7F63D1CAu,
        0x131C91F7u, 0x95A33C63u, 0xC74D61F8u, 0xB518E820u,
    };
    for (size_t len = 0; len <= 31; ++len) {
        uint32_t g = crc32_ieee_802_3(buf, len);
        if (g != pattern_expected[len]) {
            printf("FAIL  pattern         len=%4zu  exp=0x%08X"
                   "  got=0x%08X\n", len, pattern_expected[len], g);
            ++failures;
        }
    }
    printf("(pattern sweep: 32 lengths, 0..31 bytes)\n");

    if (failures == 0) {
        puts("PASS  all CRC-32 IEEE vectors match");
        return 0;
    }
    printf("FAIL  %d mismatch(es)\n", failures);
    return 1;
}
