"""Emit `memreq_records.inc` and `memreq_pin_hot.inc` NASM source.

Step 5a is x86_64-only (aarch64 deferred per task #29), so this
emitter targets NASM syntax. Each region renders as one labeled
48-byte record in the `.memreq` section; the record content is
the same 48-byte layout the existing 7-arg macro in
`arch/x86_64/memory/memreq.inc` would have produced, just emitted
as raw `db`/`dw`/`dd`/`dq` directives (the macro's "step 3"
label-copy mechanism is unlanded — codegen sidesteps that path
entirely by writing the bytes itself).

Hot-tier pins (`memreq_pin_hot.inc`) emit a `mov` per hot region,
loading `assigned_addr` into the next slot of the x86_64 hot
register pool from D066 Q-B (r15 today; budget overflow raises
at codegen time per the budget enforcement in `cli.py`).
"""

from __future__ import annotations

from memreq_codegen.encoding import (
    ALIGN_BYTECODE_BYTES,
    SIZE_BYTECODE_BYTES,
    encode_lit_bytecode,
    fnv1a_32,
)
from memreq_codegen.schema import RegionDecl

# x86_64 hot-tier register pool from D066 Q-B. The allocator's
# reverse-bump pointer also uses r15 during init, but the allocator
# pushes/pops it across its own scope (allocator.S:102, 304) and
# kernel_main_64 starts after the allocator returns — so the slot
# is free when the pin emits. Public so the CLI can derive the
# per-arch hot-tier budget from `len(HOT_POOL_X86_64)` instead of
# tracking the count in a second constant.
HOT_POOL_X86_64 = ("r15",)

# aarch64 hot-tier register pool from D066 Q-B. AAPCS64 callee-
# saved GPRs are x19-x28; the convention reserves x26-x28 for
# non-memreq scratch and gives the memreq hot-tier slots x19-x25
# (7 slots). Strict declaration order: first hot region claims
# x19, next x20, etc.
HOT_POOL_AARCH64 = ("x19", "x20", "x21", "x22", "x23", "x24", "x25")

# Lifetime / tier enum-to-wire conversions. The lifetime byte's
# wire values come from `tooling/src/memlayout/types.py:Lifetime`.
_LIFETIME_BYTE = {
    "steady_state": 0,
    "init_only": 1,
    "immutable_after_init": 2,
    "stack": 3,
}

# Record offset of `assigned_addr` — matches MR_OFF_ASSIGNED_ADDR
# in arch/x86_64/memory/allocator.S:58. Used by the hot-tier pin
# emitter when loading via the `__memreq_assigned__<name>` symbol.
_MR_OFF_ASSIGNED_ADDR_FROM_ASSIGNED = 0


def emit_records_x86_64(regions: list[RegionDecl]) -> str:
    """Render the NASM source for `memreq_records.inc`.

    The file ends with `__SECT__` so the `%include`-er's previous
    section is restored — callers can `%include` this anywhere
    (top of boot.S, inside `.text`, etc.) without leaking the
    `.memreq` section into subsequent code.
    """
    parts = [
        "; Auto-generated by tooling/memreq_codegen/. Do not edit.\n",
        "; Source: regions.yaml.\n",
        "\n",
        # D066 Q-C: section flags resolve to alloc + write. The
        # allocator mutates `assigned_addr` and `assigned_size`
        # in place at runtime. The matching aarch64 emitter uses
        # `"aw"`.
        "[section .memreq progbits alloc noexec write "
        "align=8]\n",
    ]
    for region in regions:
        parts.append(_emit_one_record_x86_64(region))
    parts.append("\n__SECT__\n")
    return "".join(parts)


def emit_pins_x86_64(regions: list[RegionDecl]) -> str:
    """Render the NASM source for `memreq_pin_hot.inc`.

    Hot-tier regions are pinned in declaration order to the
    `HOT_POOL_X86_64` slots. Refuses if the hot count exceeds the
    pool — defends against callers that bypass the CLI's budget
    check (e.g., importing emit_pins_x86_64 directly).
    """
    hot_regions = [r for r in regions if r.tier == "hot"]
    if len(hot_regions) > len(HOT_POOL_X86_64):
        raise ValueError(
            f"{len(hot_regions)} hot regions exceed pool size "
            f"{len(HOT_POOL_X86_64)} (D066 Q-B)"
        )
    parts = [
        "; Auto-generated by tooling/memreq_codegen/. Do not edit.\n",
        "; Source: regions.yaml — hot-tier register pins (D066 Q-B).\n",
        "\n",
    ]
    if not hot_regions:
        parts.append("; (no hot-tier regions declared)\n")
        return "".join(parts)
    for slot, region in zip(HOT_POOL_X86_64, hot_regions, strict=False):
        parts.append(_emit_one_pin_x86_64(slot, region))
    return "".join(parts)


def _emit_one_record_x86_64(region: RegionDecl) -> str:
    """Emit one 48-byte memreq record as NASM directives."""
    name_hash = fnv1a_32(region.name)
    size_bc = encode_lit_bytecode(region.size, SIZE_BYTECODE_BYTES)
    align_bc = encode_lit_bytecode(region.align, ALIGN_BYTECODE_BYTES)
    lifetime_byte = _LIFETIME_BYTE[region.lifetime]
    writable_byte = 1 if region.writable else 0
    return (
        "\n"
        f"; region: {region.name} "
        f"(tier={region.tier}, lifetime={region.lifetime}, "
        f"owner={region.owner}, writable={region.writable})\n"
        f"align 8\n"
        f"global __memreq_rec__{region.name}\n"
        f"__memreq_rec__{region.name}:\n"
        f"    dd      0x{name_hash:08x}"
        f"                 ; name_hash (FNV-1a u32)\n"
        f"    {_format_db(size_bc)}  ; size_bc\n"
        f"    {_format_db(align_bc)}  ; align_bc\n"
        f"    dw      {region.owner}"
        "                          ; owner_id\n"
        f"    db      {lifetime_byte}"
        "                          ; lifetime\n"
        f"    db      {writable_byte}"
        "                          ; writable\n"
        # Defense: D066 Q-C's layout puts assigned_addr at offset 32,
        # which is naturally 8-aligned given the current bytecode
        # buffer sizes (16 + 8 = 24). If those ever change, this
        # `align 8` guards the 64-bit writes the allocator makes
        # into assigned_addr/size from becoming unaligned.
        f"align 8\n"
        f"global __memreq_assigned__{region.name}\n"
        f"__memreq_assigned__{region.name}:\n"
        "    dq      0                          ; assigned_addr\n"
        "    dq      0                          ; assigned_size\n"
        f"global __memreq_addr__{region.name}\n"
        f"__memreq_addr__{region.name} equ "
        f"__memreq_assigned__{region.name}\n"
        f"global __memreq_size__{region.name}\n"
        f"__memreq_size__{region.name} equ "
        f"__memreq_assigned__{region.name} + 8\n"
    )


def _emit_one_pin_x86_64(slot: str, region: RegionDecl) -> str:
    """Emit one `mov <slot>, [__memreq_assigned__<name>]` pin."""
    return (
        f"    mov     {slot}, "
        f"[__memreq_assigned__{region.name} + "
        f"{_MR_OFF_ASSIGNED_ADDR_FROM_ASSIGNED}]"
        f"   ; pin {region.name}\n"
    )


def _format_db(data: bytes) -> str:
    """Format a byte sequence as `db 0xNN, 0xNN, ...`."""
    cells = ", ".join(f"0x{b:02x}" for b in data)
    return f"db      {cells}"


def emit_records_aarch64(regions: list[RegionDecl]) -> str:
    """Render the GNU-as source for `memreq_records.inc` on aarch64.

    Same 48-byte record layout as the x86_64 emitter (D066 Q-C);
    only the assembler syntax differs. The file ends with the
    previously-active section restoration via `.previous` so a
    `.include`-er's surrounding section context is preserved.
    """
    parts = [
        "// Auto-generated by tooling/memreq_codegen/. Do not edit.\n",
        "// Source: regions.yaml.\n",
        "\n",
        '.pushsection .memreq, "aw", %progbits\n',
    ]
    for region in regions:
        parts.append(_emit_one_record_aarch64(region))
    parts.append("\n.popsection\n")
    return "".join(parts)


def emit_pins_aarch64(regions: list[RegionDecl]) -> str:
    """Render the GNU-as source for `memreq_pin_hot.inc` on aarch64.

    Each hot-tier region takes the next slot in `HOT_POOL_AARCH64`,
    loaded via `ldr xN, =<assigned_label>; ldr xN, [xN]` — the
    pair loads the symbol's address into xN, then dereferences to
    pick up the allocator-written `assigned_addr`. Refuses if hot
    count exceeds pool size (defense-in-depth; CLI also checks).
    """
    hot_regions = [r for r in regions if r.tier == "hot"]
    if len(hot_regions) > len(HOT_POOL_AARCH64):
        raise ValueError(
            f"{len(hot_regions)} hot regions exceed pool size "
            f"{len(HOT_POOL_AARCH64)} (D066 Q-B)"
        )
    parts = [
        "// Auto-generated by tooling/memreq_codegen/. Do not edit.\n",
        "// Source: regions.yaml — hot-tier register pins (D066 Q-B).\n",
        "\n",
    ]
    if not hot_regions:
        parts.append("// (no hot-tier regions declared)\n")
        return "".join(parts)
    for slot, region in zip(
        HOT_POOL_AARCH64, hot_regions, strict=False,
    ):
        parts.append(_emit_one_pin_aarch64(slot, region))
    return "".join(parts)


def _emit_one_record_aarch64(region: RegionDecl) -> str:
    """Emit one 48-byte memreq record as GNU-as directives."""
    name_hash = fnv1a_32(region.name)
    size_bc = encode_lit_bytecode(region.size, SIZE_BYTECODE_BYTES)
    align_bc = encode_lit_bytecode(region.align, ALIGN_BYTECODE_BYTES)
    lifetime_byte = _LIFETIME_BYTE[region.lifetime]
    writable_byte = 1 if region.writable else 0
    return (
        "\n"
        f"// region: {region.name} "
        f"(tier={region.tier}, lifetime={region.lifetime}, "
        f"owner={region.owner}, writable={region.writable})\n"
        f".balign 8\n"
        f".global __memreq_rec__{region.name}\n"
        f"__memreq_rec__{region.name}:\n"
        f"    .word   0x{name_hash:08x}"
        f"                 // name_hash (FNV-1a u32)\n"
        f"    {_format_byte_dotbyte(size_bc)}  // size_bc\n"
        f"    {_format_byte_dotbyte(align_bc)}  // align_bc\n"
        f"    .short  {region.owner}"
        "                          // owner_id\n"
        f"    .byte   {lifetime_byte}"
        "                          // lifetime\n"
        f"    .byte   {writable_byte}"
        "                          // writable\n"
        # Defense (mirrors the x86_64 emitter): guards the
        # allocator's 64-bit writes from misalignment if the
        # bytecode buffer sizes ever change. AArch64 strict-
        # alignment mode would fault on a misaligned 8-byte
        # access; this explicit `.balign 8` is a no-op today
        # (offset 32 is already 8-aligned) and the safety net for
        # tomorrow.
        f".balign 8\n"
        f".global __memreq_assigned__{region.name}\n"
        f"__memreq_assigned__{region.name}:\n"
        "    .quad   0                          // assigned_addr\n"
        "    .quad   0                          // assigned_size\n"
        f".global __memreq_addr__{region.name}\n"
        f".equ __memreq_addr__{region.name}, "
        f"__memreq_assigned__{region.name}\n"
        f".global __memreq_size__{region.name}\n"
        f".equ __memreq_size__{region.name}, "
        f"__memreq_assigned__{region.name} + 8\n"
    )


def _emit_one_pin_aarch64(slot: str, region: RegionDecl) -> str:
    """Emit one `ldr xN, =assigned; ldr xN, [xN]` pin.

    First instruction loads the symbol's address into the slot;
    second dereferences to pick up the allocator-written addr.
    GNU as resolves `ldr xN, =sym` via the literal pool — an 8-byte
    qword (the symbol's 64-bit address) placed at the next `.ltorg`
    or end of the current section.
    """
    return (
        f"    ldr     {slot}, =__memreq_assigned__{region.name}\n"
        f"    ldr     {slot}, [{slot}]"
        f"   // pin {region.name}\n"
    )


def _format_byte_dotbyte(data: bytes) -> str:
    """Format a byte sequence as `.byte 0xNN, 0xNN, ...`."""
    cells = ", ".join(f"0x{b:02x}" for b in data)
    return f".byte   {cells}"
