"""Emit `memreq_records.inc` and `memreq_pin_hot.inc` NASM source.

Step 5a is x86_64-only (aarch64 deferred per task #29), so this
emitter targets NASM syntax. Each region renders as one labeled
48-byte record in the `.memreq` section; the record content is
the same 48-byte layout the existing 7-arg macro in
`arch/x86_64/memory/memreq.inc` would have produced, just emitted
as raw `db`/`dw`/`dd`/`dq` directives (the macro's "step 3"
label-copy mechanism is unlanded — codegen sidesteps that path
entirely by writing the bytes itself).

Hot-tier pins (`memreq_pin_hot.inc`) emit a `mov` per hot region,
loading `assigned_addr` into the next slot of the x86_64 hot
register pool from D066 Q-B (r15 today; budget overflow raises
at codegen time per the budget enforcement in `cli.py`).
"""

from __future__ import annotations

from memreq_codegen.encoding import (
    ALIGN_BYTECODE_BYTES,
    SIZE_BYTECODE_BYTES,
    encode_lit_bytecode,
    fnv1a_32,
)
from memreq_codegen.schema import RegionDecl

# x86_64 hot-tier register pool from D066 Q-B. The allocator's
# reverse-bump pointer also uses r15 during init, but the allocator
# pushes/pops it across its own scope (allocator.S:102, 304) and
# kernel_main_64 starts after the allocator returns — so the slot
# is free when the pin emits.
_X86_64_HOT_POOL = ("r15",)

# Lifetime / tier enum-to-wire conversions. The lifetime byte's
# wire values come from `tooling/src/memlayout/types.py:Lifetime`.
_LIFETIME_BYTE = {
    "steady_state": 0,
    "init_only": 1,
    "immutable_after_init": 2,
    "stack": 3,
}

# Record offset of `assigned_addr` — matches MR_OFF_ASSIGNED_ADDR
# in arch/x86_64/memory/allocator.S:58. Used by the hot-tier pin
# emitter when loading via the `__memreq_assigned__<name>` symbol.
_MR_OFF_ASSIGNED_ADDR_FROM_ASSIGNED = 0


def emit_records_x86_64(regions: list[RegionDecl]) -> str:
    """Render the NASM source for `memreq_records.inc`.

    The file ends with `__SECT__` so the `%include`-er's previous
    section is restored — callers can `%include` this anywhere
    (top of boot.S, inside `.text`, etc.) without leaking the
    `.memreq` section into subsequent code.
    """
    parts = [
        "; Auto-generated by tooling/memreq_codegen/. Do not edit.\n",
        "; Source: regions.yaml.\n",
        "\n",
        "[section .memreq progbits alloc noexec nowrite "
        "align=8]\n",
    ]
    for region in regions:
        parts.append(_emit_one_record_x86_64(region))
    parts.append("\n__SECT__\n")
    return "".join(parts)


def emit_pins_x86_64(regions: list[RegionDecl]) -> str:
    """Render the NASM source for `memreq_pin_hot.inc`.

    Hot-tier regions are pinned in declaration order to the
    `_X86_64_HOT_POOL` slots. Budget exceedance is enforced at
    the CLI layer (see `cli.py`); this function trusts that the
    caller has already validated the hot count.
    """
    hot_regions = [r for r in regions if r.tier == "hot"]
    parts = [
        "; Auto-generated by tooling/memreq_codegen/. Do not edit.\n",
        "; Source: regions.yaml — hot-tier register pins (D066 Q-B).\n",
        "\n",
    ]
    if not hot_regions:
        parts.append("; (no hot-tier regions declared)\n")
        return "".join(parts)
    for slot, region in zip(_X86_64_HOT_POOL, hot_regions, strict=False):
        parts.append(_emit_one_pin_x86_64(slot, region))
    return "".join(parts)


def _emit_one_record_x86_64(region: RegionDecl) -> str:
    """Emit one 48-byte memreq record as NASM directives."""
    name_hash = fnv1a_32(region.name)
    size_bc = encode_lit_bytecode(region.size, SIZE_BYTECODE_BYTES)
    align_bc = encode_lit_bytecode(region.align, ALIGN_BYTECODE_BYTES)
    lifetime_byte = _LIFETIME_BYTE[region.lifetime]
    writable_byte = 1 if region.writable else 0
    return (
        "\n"
        f"; region: {region.name} "
        f"(tier={region.tier}, lifetime={region.lifetime}, "
        f"owner={region.owner}, writable={region.writable})\n"
        f"align 8\n"
        f"global __memreq_rec__{region.name}\n"
        f"__memreq_rec__{region.name}:\n"
        f"    dd      0x{name_hash:08x}"
        f"                 ; name_hash (FNV-1a u32)\n"
        f"    {_format_db(size_bc)}  ; size_bc\n"
        f"    {_format_db(align_bc)}  ; align_bc\n"
        f"    dw      {region.owner}"
        "                          ; owner_id\n"
        f"    db      {lifetime_byte}"
        "                          ; lifetime\n"
        f"    db      {writable_byte}"
        "                          ; writable\n"
        f"global __memreq_assigned__{region.name}\n"
        f"__memreq_assigned__{region.name}:\n"
        "    dq      0                          ; assigned_addr\n"
        "    dq      0                          ; assigned_size\n"
        f"global __memreq_addr__{region.name}\n"
        f"__memreq_addr__{region.name} equ "
        f"__memreq_assigned__{region.name}\n"
        f"global __memreq_size__{region.name}\n"
        f"__memreq_size__{region.name} equ "
        f"__memreq_assigned__{region.name} + 8\n"
    )


def _emit_one_pin_x86_64(slot: str, region: RegionDecl) -> str:
    """Emit one `mov <slot>, [__memreq_assigned__<name>]` pin."""
    return (
        f"    mov     {slot}, "
        f"[__memreq_assigned__{region.name} + "
        f"{_MR_OFF_ASSIGNED_ADDR_FROM_ASSIGNED}]"
        f"   ; pin {region.name}\n"
    )


def _format_db(data: bytes) -> str:
    """Format a byte sequence as `db 0xNN, 0xNN, ...`."""
    cells = ", ".join(f"0x{b:02x}" for b in data)
    return f"db      {cells}"
